Update sendstats

diff --git a/scripts/sendstats b/scripts/sendstats
--- a/scripts/sendstats
+++ b/scripts/sendstats
@@ -1,116 +1,154 @@
-#!/bin/sh
+#!/bin/bash
+#
+# chkconfig: 345 97 05
+# description: Java deamon script
 #
 
-# description: Send-Stats to media server
+# Set this to your Java installation
+JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64
 
+serviceNameLo="sendstats"                                       # service name with the first letter in lowercase
+serviceName="sendstats"                                         # service name
+serviceUser="root"                                        # OS user name for the service
+serviceGroup="root"                                       # OS group name for the service
+applDir="/root/kms-monitoring-java"                           # home directory of the service application
+serviceUserHome="/root/"                                      # home directory of the service user
+serviceLogFile="/var/log/$serviceNameLo.log"                  # log file for StdOut/StdErr
+maxShutdownTime=15                                            # maximum number of seconds to wait for the daemon to terminate normally
+pidFile="/var/run/$serviceNameLo.pid"                         # name of PID file (PID = process ID number)
+javaCommand="java"                                            # name of the Java launcher without the path
+javaExe="$JAVA_HOME/bin/$javaCommand"                         # file name of the Java application launcher executable
 
-### BEGIN INIT INFO
-# Provides:          monitoring-stats-daemon
-# Required-Start:    $remote_fs $network $kurento-media-server-6.0
-# Required-Stop:     $remote_fs
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Monitoring stats daemon
-### END INIT INFO
+EXTERNAL_IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
+instance_name=$(curl http://169.254.169.254/latest/meta-data/hostname)
+instance_name=${instance_name::-10}
 
-# Check the application status
-#
-# This function checks if the application is running
-check_status() {
-
-  # Running ps with some arguments to check if the PID exists
-  # -C : specifies the command name
-  # -o : determines how columns must be displayed
-  # h : hides the data header
-  s=`ps -C 'java -cp httpcore-4.3.1.jar' -o pid h`
-
-  # If somethig was returned by the ps command, this function returns the PID
-  if [ $s ] ; then
-    return $s
-  fi
-
-  # In any another case, return 0
-  return 0
-
+javaArgs="-DHOST_NAME=$instance_name -Dkms.ws.uri=ws://$EXTERNAL_IP:8888/kurento -cp $applDir/httpcore-4.3.1.jar:$applDir/websocket-api-9.3.0.M1.jar:$applDir/jetty-io-9.3.0.M1.jar:$applDir/jetty-util-9.3.0.M1.jar:$applDir/websocket-common-9.3.0.M1.jar:$applDir/websocket-client-9.3.0.M1.jar:$applDir/gson-2.3.1.jar:$applDir/guava-18.0.jar:$applDir/slf4j-api-1.7.5.jar:$applDir/kurento-jsonrpc-client-6.0.0-SNAPSHOT.jar:$applDir/kurento-commons-6.0.0-SNAPSHOT.jar:$applDir/kurento-client-6.0.0-SNAPSHOT.jar:$applDir/target/kms-monitoring-java-6.0.0-SNAPSHOT.jar org.kurento.tutorial.kmsmonitor.SendStats"
+javaCommandLine="$javaExe $javaArgs"                          # command line to start the Java service application
+javaCommandLineKeyword="kms-monitoring-java-6.0.0-SNAPSHOT.jar"       # a keyword that occurs on the commandline, used to detect an already running service process and to distinguish it from others
+ 
+# Makes the file $1 writable by the group $serviceGroup.
+function makeFileWritable {
+   local filename="$1"
+   touch $filename || return 1
+   chgrp $serviceGroup $filename || return 1
+   chmod g+w $filename || return 1
+   return 0; }
+ 
+# Returns 0 if the process with PID $1 is running.
+function checkProcessIsRunning {
+   local pid="$1"
+   if [ -z "$pid" -o "$pid" == " " ]; then return 1; fi
+   if [ ! -e /proc/$pid ]; then return 1; fi
+   return 0; }
+ 
+# Returns 0 if the process with PID $1 is our Java service process.
+function checkProcessIsOurService {
+   local pid="$1"
+   if [ "$(ps -p $pid --no-headers -o comm)" != "$javaCommand" ]; then return 1; fi
+   grep -q --binary -F "$javaCommandLineKeyword" /proc/$pid/cmdline
+   if [ $? -ne 0 ]; then return 1; fi
+   return 0; }
+ 
+# Returns 0 when the service is running and sets the variable $pid to the PID.
+function getServicePID {
+   if [ ! -f $pidFile ]; then return 1; fi
+   pid="$(<$pidFile)"
+   checkProcessIsRunning $pid || return 1
+   checkProcessIsOurService $pid || return 1
+   return 0; }
+ 
+function startServiceProcess {
+   cd $applDir || return 1
+   rm -f $pidFile
+   makeFileWritable $pidFile || return 1
+   makeFileWritable $serviceLogFile || return 1
+   cmd="nohup $javaCommandLine >>$serviceLogFile 2>&1 & echo \$! >$pidFile"
+   su -m $serviceUser -s $SHELL -c "$cmd" || return 1
+   sleep 0.1
+   pid="$(<$pidFile)"
+   if checkProcessIsRunning $pid; then :; else
+      echo -ne "\n$serviceName start failed, see logfile."
+      return 1
+   fi
+   return 0; }
+ 
+function stopServiceProcess {
+   kill $pid || return 1
+   for ((i=0; i<maxShutdownTime*10; i++)); do
+      checkProcessIsRunning $pid
+      if [ $? -ne 0 ]; then
+         rm -f $pidFile
+         return 0
+         fi
+      sleep 0.1
+      done
+   echo -e "\n$serviceName did not terminate within $maxShutdownTime seconds, sending SIGKILL..."
+   kill -s KILL $pid || return 1
+   local killWaitTime=15
+   for ((i=0; i<killWaitTime*10; i++)); do
+      checkProcessIsRunning $pid
+      if [ $? -ne 0 ]; then
+         rm -f $pidFile
+         return 0
+         fi
+      sleep 0.1
+      done
+   echo "Error: $serviceName could not be stopped within $maxShutdownTime+$killWaitTime seconds!"
+   return 1; }
+ 
+function startService {
+   getServicePID
+   if [ $? -eq 0 ]; then echo -n "$serviceName is already running"; RETVAL=0; return 0; fi
+   echo -n "Starting $serviceName   "
+   startServiceProcess
+   if [ $? -ne 0 ]; then RETVAL=1; echo "failed"; return 1; fi
+   echo "started PID=$pid"
+   RETVAL=0
+   return 0; }
+ 
+function stopService {
+   getServicePID
+   if [ $? -ne 0 ]; then echo -n "$serviceName is not running"; RETVAL=0; echo ""; return 0; fi
+   echo -n "Stopping $serviceName   "
+   stopServiceProcess
+   if [ $? -ne 0 ]; then RETVAL=1; echo "failed"; return 1; fi
+   echo "stopped PID=$pid"
+   RETVAL=0
+   return 0; }
+ 
+function checkServiceStatus {
+   echo -n "Checking for $serviceName:   "
+   if getServicePID; then
+    echo "running PID=$pid"
+    RETVAL=0
+   else
+    echo "stopped"
+    RETVAL=3
+   fi
+   return 0; }
+ 
+function main {
+   RETVAL=0
+   case "$1" in
+      start)                                               # starts the Java program as a Linux service
+         startService
+         ;;
+      stop)                                                # stops the Java program service
+         stopService
+         ;;
+      restart)                                             # stops and restarts the service
+         stopService && startService
+         ;;
+      status)                                              # displays the service status
+         checkServiceStatus
+         ;;
+      *)
+         echo "Usage: $0 {start|stop|restart|status}"
+         exit 1
+         ;;
+      esac
+   exit $RETVAL
 }
-
-# Starts the application
-start() {
-
-  # At first checks if the application is already started calling the check_status
-  # function
-  check_status
-
-  # $? is a special variable that hold the "exit status of the most recently executed
-  # foreground pipeline"
-  pid=$?
-
-  if [ $pid -ne 0 ] ; then
-    echo "The application is already started"
-    exit 1
-  fi
-
-  # If the application isn't running, starts it
-  echo -n "Starting application: "
-  sleep 10
-  # Redirects default and error output to a log file
-  #java -jar /path/to/application.jar >> /path/to/logfile 2>&1 &
-  cd ~/kms-monitoring-java && java -cp httpcore-4.3.1.jar:websocket-api-9.3.0.M1.jar:jetty-io-9.3.0.M1.jar:jetty-util-9.3.0.M1.jar:websocket-common-9.3.0.M1.jar:websocket-client-9.3.0.M1.jar:gson-2.3.1.jar:guava-18.0.jar:slf4j-api-1.7.5.jar:kurento-jsonrpc-client-6.0.0-SNAPSHOT.jar:kurento-commons-6.0.0-SNAPSHOT.jar:kurento-client-6.0.0-SNAPSHOT.jar:target/kms-monitoring-java-6.0.0-SNAPSHOT.jar org.kurento.tutorial.kmsmonitor.SendStats >> /var/log/sendstats.log 2>&1 &
-  echo "OK"
-}
-
-# Stops the application
-stop() {
-
-  # Like as the start function, checks the application status
-  check_status
-
-  pid=$?
-
-  if [ $pid -eq 0 ] ; then
-    echo "Application is already stopped"
-    exit 1
-  fi
-
-  # Kills the application process
-  echo -n "Stopping application: "
-  kill -9 $pid &
-  echo "OK"
-}
-
-# Show the application status
-status() {
-
-  # The check_status function, again...
-  check_status
-
-  # If the PID was returned means the application is running
-  if [ $? -ne 0 ] ; then
-    echo "Application is started"
-  else
-    echo "Application is stopped"
-  fi
-
-}
-
-# Main logic, a simple case to call functions
-case "$1" in
-  start)
-    start
-    ;;
-  stop)
-    stop
-    ;;
-  status)
-    status
-    ;;
-  restart|reload)
-    stop
-    start
-    ;;
-  *)
-    echo "Usage: $0 {start|stop|restart|reload|status}"
-    exit 1
-esac
-
-exit 0
+ 
+main $1
